kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: climeatdb
  labels:
    app: climeatdb
    tier: db
spec:
  serviceName: "climeatdb"
  replicas: 1
  selector:
    matchLabels:
      app: climeatdb
      tier: db
  template:
    metadata:
      labels:
        app: climeatdb
        tier: db
    spec:
      serviceAccountName: default
      containers:
      - name: climeatdb
        image: postgres:latest
        env:
          - name: POSTGRES_DB
            value: climeat
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: climeat-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: climeat-secret
                key: POSTGRES_PASSWORD
        ports:
          - containerPort: 5432
            name: postgresdb
        resources:
          requests:
            cpu: 2000m
            memory: 1Gi
          limits:
            cpu: 8000m
            memory: 4Gi
        volumeMounts:
          - name: postgresdb
            mountPath: /var/lib/postgresql/data
            subPath: postgres
          - name: dshm
            mountPath: /dev/shm
      volumes:
      - name: postgresdb
        emptyDir: {}
      - name: dshm
        emptyDir: {}