version: "3.7"
services:
    climeat:
        build:
            context: ./services/climeat/.
            dockerfile: docker/Dockerfile
        ports:
            - "8009:8009"
        environment:
            - AGENT_HOSTNAME=otel-collector
            - OTEL_PYTHON_LOG_CORRELATION=true
        networks:
            - norse
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.climeat.loadbalancer.server.port=8009"
            - "traefik.http.routers.climeat.rule=Host(`climeat.localhost`)"
            - "traefik.http.routers.climeat.entrypoints=web"
            - "app=climeat"
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/loki/api/v1/push'
                labels: app
networks:
    norse:
        driver: bridge