version: "3.7"
services:
    recipes:
        build:
            context: ./services/recipes/.
            dockerfile: docker/Dockerfile
        ports:
            - "8009:8009"
        environment:
            - AGENT_HOSTNAME=otel-collector
            - OTEL_PYTHON_LOG_CORRELATION=true
        networks:
            - norse
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.recipes.loadbalancer.server.port=8009"
            - "traefik.http.routers.recipes.rule=Host(`recipes.localhost`)"
            - "traefik.http.routers.recipes.entrypoints=web"
            - "app=recipes"
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/loki/api/v1/push'
                labels: app
    otel-collector:
        image: otel/opentelemetry-collector:latest
        volumes:
            - ./config/otel-collector.yaml:/config/otel-collector.yaml
        command:
            - --config=/config/otel-collector.yaml
        networks:
            - norse
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/api/v1/push'
networks:
    norse:
        driver: bridge